### ISSUE TITLE
Membership observations shows duplicates

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#108]

**Comment by RobertAKARobin** [comment]
Ditto for membership / attendances

**Comment by mattscilipoti** [comment]
Looking into use Set for this.

**Comment by RobertAKARobin** [comment]
What's set?

**Comment by RobertAKARobin** [comment]
RAILS HAS SETS? And I didn't know?! I've missed those so much coming from Java!

**Comment by mattscilipoti** [comment]
re: PR #151

**Comment by mattscilipoti** [comment]
Can't verify due to Issue #158
