### ISSUE TITLE
error logging in, `getaddrinfo` 

### ISSUE THREAD

**Issue by adambray** [ga-dc/garnet#135]
Quitting chrome fixed it, so I suspect there are some edge cases involving sessions and our login.

Can't repo right now.

**Comment by adambray** [comment]
Full error message displayed to user:

```
getaddrinfo: Name or service not known
```

**Comment by adambray** [comment]
Repo'd by logging out and trying to sign back in with github

**Comment by jshawl** [comment]
I can reproduce by logging out and logging in in production, but not in development

**Comment by RobertAKARobin** [comment]
A grep shows that this isn't anything in our code. Only place it's mentioned is `tmp/unicorn.sock`

**Comment by mattscilipoti** [comment]
OI just got this message when selecting a Student to create an Observation on.

**Comment by mattscilipoti** [comment]
Remembered that Logout/login may fix it ^.  It did.
