### ISSUE TITLE
Bug: duplicate observations

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/garnet#147]
Reproduce: create an observation

Example: http://garnet.wdidc.org/groups/ga_wdi_dc_7/users/jotalp

**Comment by mattscilipoti** [comment]
First one had issues saving (long spinner).  Second one seemed fine.  Both were duplicated.

**Comment by RobertAKARobin** [comment]
Duplicate of https://github.com/ga-dc/garnet/issues/108
