### ISSUE TITLE
Set memberships as "inactive" for dropped students

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#163]

**Comment by andrewsunglaekim** [comment]
what would this look like, a boolean value on the memberships model? or should it be a string? :ie, "current student", "inactive", "graduated" etc etc.

**Comment by RobertAKARobin** [comment]
I'd say an integer status column, maybe? Like how attendances and submissions have 0 - 2?

I really prefer integer statuses to string statuses, since it makes it much easier to change the name of the different statuses, and you can use SQL arithmetic methods on those columns.

**Comment by adambray** [comment]
ActiveRecord enums would be the right way to do this. I'm about to take a stab at a PR for this...

**Comment by adambray** [comment]
Completed.
