### ISSUE TITLE
Error: undefined local variable or method `enable' for #<#<Class:0x000000061e2b88>:0x000000061e1a30>

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/garnet#178]
1. http://garnet.wdidc.org/groups/ga_wdi_dc_7/observations
2. Click on a student

**Comment by jshawl** [comment]
@RobertAKARobin please reference issue when fixing in commit message:

```
git commit -m "fixes #178"
```

**Comment by RobertAKARobin** [comment]
Huh. I didn't think I'd fixed it

**Comment by jshawl** [comment]
https://github.com/ga-dc/garnet/commit/86888af879d2e696cef86473f7f787b6b99e6e6d#diff-0137ddd9d0bb7aedbad7303715ec8a6aL6

**Comment by RobertAKARobin** [comment]
Thank you
