### ISSUE TITLE
Seeds file

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/garnet#193]
Currently seed file doesn't generate any user or groups. I see a `test_seed.rb` file in a different folder. I ended up just copying and pasting that code into my rails console to genereate seed data. In general though, we need a more robust seed file to include some dummy events/assignments/observations.

**Comment by jshawl** [comment]
you can execute test seeds with `rake db:seed:test_seed`, but why?

**Comment by adambray** [comment]
Fixed with latest seed updates.
