### ISSUE TITLE
prevent two events from being created on the same date

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#206]
or just have a "take todays attendance" button

**Comment by andrewsunglaekim** [comment]
this may be a feature we want in our app, re: creating 2 events on the same date

**Comment by jshawl** [comment]
Yep this PR should solve the underlying issue of having duplicate events. https://github.com/ga-dc/garnet/pull/241

**Comment by RobertAKARobin** [comment]
@jshawl You see my comments on it?
