### ISSUE TITLE
Correct attendance data (prior to sharing status/report card with students)

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/garnet#209]
http://garnet.wdidc.org/groups/ga_wdi_dc_7#attendance

- for 10/13
  - [X] Confirm "mariia" is "present" for other 10/13 event.
  - [x] Delete extra, http://garnet.wdidc.org/events/1.
- for 10/14: 
  - [x] Delete one for GA group: http://garnet.wdidc.org/events/4
  - [x] Add one for ga_wdi_dc_7. #deicsion Remove event if data was unknown.
- for 10/15
  - [x] Delete extra for 10/15: http://garnet.wdidc.org/events/5
- [x] Update date for events/11 to `10/20/2015 09:00am`. It was created on 10/20, but date was incorrectly set to 10/21.
- [x] re-add 10/21 from Robin's pg_dump.
- ~~identify and remove duplicate for 10/27~~ A few hours after I added this, there was no duplicate.  My assumption is that I meant 10/28.  10/28 should have 2 entries.  One for th day, one for Project 1 presentations.

**Comment by RobertAKARobin** [comment]
May be useful: https://github.com/ga-dc/garnet/commit/951f92bde6a7348616b6ab775af17c7047f6a5e4

**Comment by mattscilipoti** [comment]
While verifying this, I identified #226

**Comment by RobertAKARobin** [comment]
I think this is probably due to people not seeing there's an existing attendance and creating a new one...?

**Comment by mattscilipoti** [comment]
How can we avoid duplicates in the future?  We don't want to keep doing this while students are checking it.  Easy, short term solution: unique constraint on events.date.

**Comment by mattscilipoti** [comment]
/me Merging the 2 10/22 entries now.

**Comment by RobertAKARobin** [comment]
How about this?

https://github.com/ga-dc/garnet/pull/227

**Comment by mattscilipoti** [comment]
#228 should help too.

**Comment by mattscilipoti** [comment]
LOL.  Great minds think alike.  Removing #227.  But, still that's a poor stop gap (not refreshed, started same time, etc).  Let's stop it from happening.

**Comment by RobertAKARobin** [comment]
I'd rather not, because in the future we may want to have multiple events on the same day.

**Comment by mattscilipoti** [comment]
When merging, tie goes to the student.  If one says tardy and another says present - I'm going with present.

**Comment by mattscilipoti** [comment]
Crap.  This is a lot of changes.  I'm going to wait to discuss in person.  This worries me that this data can be so different.  WTF is happening?  
<img width="1280" alt="wdi7_compareattendance_10_22" src="https://cloud.githubusercontent.com/assets/31929/10970068/36ffb41a-839a-11e5-92bf-7f68d970628c.png">

**Comment by RobertAKARobin** [comment]
Huh. That's weird.

**Comment by mattscilipoti** [comment]
@RobertAKARobin I vote we make it safe today. And discuss the future.  This is a mess.

**Comment by RobertAKARobin** [comment]
The only situation on which I see that is Thursday, 10/22. I'm pretty sure that's just because we didn't have a way to delete events at that point, and someone created a new event without seeing one already existed. Hence, the other event is called "Actual October 22" (lol)

I don't think it's something we need to worry about going forward. It's a mess just for that one day.

**Comment by RobertAKARobin** [comment]
Also, as Adam pointed out, on 10/22 the default date for new events was "tomorrow at 9:00am". Combined with there not being a way to delete events, it's sorta no wonder things got bouffed up.

**Comment by mattscilipoti** [comment]
Robin and I are verifying data in his local copy.  We have verified that events/11 (labeled 10/21) was created on 10/20.  Recommend updating the event.date to `10/20/2015 09:00am`.

**Comment by RobertAKARobin** [comment]
Just did

**Comment by mattscilipoti** [comment]
All known issues have been corrected.
