### ISSUE TITLE
Attendance unusable on mobile

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#217]
![](https://dl.dropboxusercontent.com/s/lodndcysvatklvq/2015-11-02%2008.47.01.png?dl=0)

**Comment by RobertAKARobin** [comment]
Can you re-screenshot? This one is broken.

**Comment by RobertAKARobin** [comment]
I can merge in a hotfix -- just removing `table-layout: fixed` and change `Delete` to `x`

**Comment by jshawl** [comment]
let the fruit hang low!

**Comment by RobertAKARobin** [comment]
Just don't want to inhibit anyone's ability to take attendance since that's pretty pressing.

https://github.com/ga-dc/garnet/pull/216

Merge if you want it; close otherwise
