### ISSUE TITLE
When attempting to create a new event, warn the user if an event already exists for the day.

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#237]
An alert box or something.

**Comment by jshawl** [comment]
other idea: automatically create events once per day for 9:00am

default form field is for 9am. Active record validation validates uniqueness. If you want to create a second attendance event, you'll have to manually change the time

**Comment by jshawl** [comment]
other idea: if even exists for today, hide the "create event" form. User has to click a button to show it -- text says "event already exists today click this button to create a new event anyway"

**Comment by RobertAKARobin** [comment]
Matt and I were talking about automatically creating an attendance per day. My pushback is that we may want to have multiple events on one day. For example, on the Project 1 presentations day, we had one event for physically being there, and a second event for presenting. Plus, how to prevent it creating events on holidays? I'd rather just have some kinda warning.

**Comment by jshawl** [comment]
personal recommendation is

>other idea: if even exists for today, hide the "create event" form. User has to click a button to show it -- text says "event already exists today click this button to create a new event anyway"

**Comment by jshawl** [comment]
@RobertAKARobin can i do this? am interested :)

**Comment by RobertAKARobin** [comment]
Hell yeah! You're the PM. I'm just an opinionated developer.
