### ISSUE TITLE
Percent Complete and N/As

### ISSUE THREAD

**Issue by dan-ator** [ga-dc/garnet#243]
I think that the assignments listed as N/A (meaning assigned, turned in, but not yet graded) should not be included in the calculation for percent complete.  It's a small point, but I don't like seeing the percent complete so low on my "report card" when in fact I did complete them (or they aren't yet due).

**Comment by jshawl** [comment]
@dan-ator great point!!! Are you interested in contributing? Maybe `reject` those submissions that have a status of 0 ("n/a") - https://github.com/ga-dc/garnet/blob/174a1e4b611b60fc720e7e430f1fb36800fa2631/app/controllers/users_controller.rb#L29

**Comment by RobertAKARobin** [comment]
Fixed by https://github.com/ga-dc/garnet/pull/256
