### ISSUE TITLE
Verify if we need 2 copies of jQuery loaded

### ISSUE THREAD

**Issue by adambray** [ga-dc/garnet#255]
Currently jQuery is loaded via the asset pipeline, and via a script tag at the bottom of the  layout.  I don't think that's intentional, but wanted to check about that.

Additionally, the second version is 3.0.0.alpha, which I'm not sure we want. @RobertAKARobin @ebirving @jshawl, do any of you have any insight on whether we can remove it?

**Comment by RobertAKARobin** [comment]
Hah, that's funny. I'd say go for it!

**Comment by adambray** [comment]
I'm going in! Wish me luck!

**Comment by RobertAKARobin** [comment]
Fixed by https://github.com/ga-dc/garnet/pull/259
