### ISSUE TITLE
To-do not showing for submissions

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#262]

**Comment by RobertAKARobin** [comment]
Cannot reproduce. 
![screen shot 2015-11-18 at 6 04 09 pm](https://cloud.githubusercontent.com/assets/6268177/11257326/da7d9132-8e1e-11e5-8d32-bcc3f0c18049.png)

**Comment by ebirving** [comment]
I'm having a brain fart -- what's the problem?

**Comment by RobertAKARobin** [comment]
@adambray was saying that the stuff he needed to grade wasn't showing up, but I can't reproduce the error.

**Comment by ebirving** [comment]
Hmmmm
