### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by tessb** [ga-dc/garnet#285]
This happens when ever I try to sign in with github

![screen shot 2015-12-02 at 1 09 09 pm](https://cloud.githubusercontent.com/assets/12400478/11539611/f7442a24-98f5-11e5-8e16-e14a55884cbb.png)

**Comment by mattscilipoti** [comment]
Debugging steps (to be done with Tess).
- It looks like she is already signed in, try 
  - visiting "/users/tessb".
  - login via incognito tab
  - /sign_out

Follow up actions:
- "link" github to this user/pwd account, by clicking link on profile page

**Comment by mattscilipoti** [comment]
We need to reset her password.  I recommend choosing a password and assigning it via `rails c`.  
- debug@ssh user can not do this.  
- `$ ssh git@garnet.wdidc.org` #-> Permission denied (publicly). @jshawl ?

**Comment by jshawl** [comment]
two options:

1 - allow debug user to run rails c
2 - add your keys to the git user's authroized_keys

**Comment by mattscilipoti** [comment]
Fix: had Tess update her user's password via `rails console` (with me).  Reminded her to link her profile to github via link on profile page.

**Comment by adambray** [comment]
@mattscilipoti what caused this initially? Is there a bug we can repo to re-trigger this broken state?

**Comment by mattscilipoti** [comment]
Solution: had Tess update her password using rails console.  After she could login, she linked her account to github using the app's feature.
