### ISSUE TITLE
Let students take their own attendance

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#288]
# Ideas:

- Put a "word of the day" on the board, which students have to enter to be marked "here"
- When the instructor creates the event, their IP is logged. When students check in, their IP is also logged. It must match (the whole things or the first 3 sections?) for the check-in to be successful.

**Comment by jshawl** [comment]
https://github.com/ga-dc/garnet/issues/281#issuecomment-162539220

**Comment by jshawl** [comment]
can just check the client's public IP address to know that they are in the building

**Comment by RobertAKARobin** [comment]
Let's do that!
