### ISSUE TITLE
assignment show page should link back to assignments index view

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/garnet#290]

**Comment by adambray** [comment]
@andrewsunglaekim can you clarify? There is no assignments index view. The closest is the group show view, which has a list of assignments as a page fragment. Is that what you want?

**Comment by andrewsunglaekim** [comment]
Oh right, the groups show page with the assignments tab open

**Comment by adambray** [comment]
Fixed inadvertently in the conversion to cohorts.
