### ISSUE TITLE
`add_admin` undefined method in test suite

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#318]
https://github.com/ga-dc/garnet/blob/0ac1a68c2040abcac670256a5ee9afeea641cde6/spec/features/attendance_spec.rb#L11

can i yank this @adambray ?

**Comment by jshawl** [comment]
to repo:

```
rspec spec/features/attendance_spec.rb 
```

**Comment by adambray** [comment]
not sure why it's undefined:
https://github.com/ga-dc/garnet/blob/0ac1a68c2040abcac670256a5ee9afeea641cde6/app/models/cohort.rb#L37

**Comment by adambray** [comment]
That may be an issue in your seed data. Is it being called on `nil`?

**Comment by jshawl** [comment]
:+1: 

adding `describe do; end;` in `features/` causes this error. moving to `spec/models/`

**Comment by adambray** [comment]
I ran that command locally and the 1 test passed
