### ISSUE TITLE
Export Cohort data as CSV files

### ISSUE THREAD

**Issue by bmartinowich** [ga-dc/garnet#348]
Would like to export Attendance, Homework, and Project scores by student, per each cohort.

**Comment by adambray** [comment]
@bmartinowich I think this'll be a CSV instead of XLS. It will still open in excel... is that ok?

**Comment by jshawl** [comment]
in progress by @jshawl

**Comment by jshawl** [comment]
@bmartinowich click "Export" - http://garnet.wdidc.org/cohorts/1 let me know what you think

**Comment by adambray** [comment]
@bmartinowich @JonRojas Would appreciate any feedback on the CSV format [here](http://garnet.wdidc.org/cohorts/1/manage).

(Click export CSV).

**Comment by andrewsunglaekim** [comment]
YO @bmartinowich @JonRojas  I WANNA CLOSE DIS ISSUE

**Comment by bmartinowich** [comment]
Sorry -- approved. Feel free to close
