### ISSUE TITLE
mantras should be self hosted?

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#361]
What if @RobertAKARobin goes rogue? why not self-host with a mantra controller?

https://github.com/ga-dc/garnet/commit/ca2367ec24be235f05d6ac1a0eb733fadbbec927#diff-822b0d0191c78dd3ebae802cf2a2a2b8R8

**Comment by RobertAKARobin** [comment]
Ooh, that's tempting.

**Comment by RobertAKARobin** [comment]
Some options:
- Create a Mantra model and pull from database. Downside: have to use database
- Create a mantras file on the WDIDC server. Downside: have to go onto the server to change it.
- Create a mantras repo, Travis it to wdidc, and let people push new mantras to it.

**Comment by jshawl** [comment]
:+1: Create a mantras repo. use raw.github.io - https://raw.githubusercontent.com/ga-dc/wdi8/master/lessons.json

**Comment by RobertAKARobin** [comment]
I thought you weren't supposed to depend on raw?

**Comment by jshawl** [comment]
recommend static json file in https://github.com/ga-dc/garnet/tree/master/public

**Comment by adambray** [comment]
:+1: for @jshawl 's last suggestion

**Comment by jshawl** [comment]
fixed in https://github.com/ga-dc/garnet/pull/368
