### ISSUE TITLE
Update deployment to use `whenever` for cron scheduling

### ISSUE THREAD

**Issue by adambray** [ga-dc/garnet#384]

**Comment by jshawl** [comment]
@adambray had to update cron manually:

because `whenever -w` did not add source to RVM environment. additionally `whenever -w` erased previous `pg_dump`

**Comment by adambray** [comment]
There's an option to whenever that won't clobber the crontab. Don't remember off the top of my head, but I'm pretty sure it's documented in the wiki for whenever

**Comment by jshawl** [comment]
:+1: next time - http://stackoverflow.com/a/10197962/850825

**Comment by adambray** [comment]
@jshawl did you fix the clobbering for pg_dump? If not, let me know so I can do that. 

-Adam
