### ISSUE TITLE
View student progress on Membership list

### ISSUE THREAD

**Issue by mattscilipoti** [ga-dc/garnet#395]
We should be able to see an overview (average observation score) of each student's progress in the Membership list.

**Comment by mattscilipoti** [comment]
This would be helpful for staff at GA, especially Instructors, Producers, and Outcomes

**Comment by nolds9** [comment]
addressed in #401

**Comment by andrewsunglaekim** [comment]
I feel like garnet had this feature and it was removed. Maybe it was just removed from a part where it didn't need to be.

**Comment by adambray** [comment]
Fixed in #401
