### ISSUE TITLE
Capybara::Poltergeist::JavascriptError

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/garnet#417]
Getting this failure when running rspec locally but Travis builds just fine when I make a PR on a branch. Installed phantomJS, so i'm still not sure what the issue is.

`TypeError: 'undefined' is not a function (evaluating 'KonamiListener.oninput.bind(instance)')`

**Comment by adambray** [comment]
Can you share the output of `phantomjs --version` and `which phantomjs`?

**Comment by andrewsunglaekim** [comment]
i have version 2.0.0

**Comment by andrewsunglaekim** [comment]
fixed, thanks adam!
