### ISSUE TITLE
Fatal error when student who has linked GH to their account tries to log in by typing in username/password

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#427]
Testy Testerson has a Github account with a username of "testerson" and a password of "foobar".

Testy creates a Garnet account linked to his Github account.

Then, Testy tries to log in to Garnet by typing in his username and password. He gets a "Something went wrong" error.

The "right" way is to click the "Sign in with Github" button.

**Comment by andrewsunglaekim** [comment]
Could not recreate this fatal error with @RobertAKARobin . 

Though during investigation found that `sign_in` action was utilizing raises that leveraged an older(now non existent) global rescuer.
