### ISSUE TITLE
ability to populate attendances for past events for new users

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/garnet#484]
Ran into this for the DOC immersive. 

Created an event, which creates an attendance for each membership that are associated to that event. But if a member joins that cohort after the event was created. There's no interface to populate those attendances without deleting the existing event and creating a new one.

**Comment by RobertAKARobin** [comment]
Scroll to the bottom for the "Manually Create Attendances":

https://garnet.wdidc.org/events/139?cohort=4&show_na=true

**Comment by andrewsunglaekim** [comment]
yeah im an idiot
