### ISSUE TITLE
student is a member but attendance aren't being generated for them

### ISSUE THREAD

**Issue by andrewsunglaekim** [ga-dc/garnet#485]
isn't auto creating attendances for that student when attendance is made, also can't manually create an attendance for student.

Interestingly enough though, attendance % present is 100%...

**Comment by RobertAKARobin** [comment]
Clear cache, maybe?

**Comment by andrewsunglaekim** [comment]
reminder : this was noticed through data vis immersive group, which github username `sunnydata` is a member but not getting attendances generated.

**Comment by andrewsunglaekim** [comment]
i don't think it was a caching issue because it should be listening to those changes?
