### ISSUE TITLE
Standardize, polish, and consolidate the UX

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#491]
This is just as important as functionality if we're going to start showing this to other people! No need to wait for UXDI support to start.

Ideas:

- Make tags more accessible: move to cohort `show` page
- Standardize headers: some are pills, some aren't
- Fewer/more standard partials. For example: submissions rows on "dashboard" page should look like submissions rows on assignment "show" page
- Move dashboard to current user's show page
- Make more mobile-friendly
- Create links to index pages for cohorts, courses, and locations
- Speed up cohort show page (see https://github.com/ga-dc/garnet/pull/482)

**Comment by amaseda** [comment]
:+1:

**Comment by RobertAKARobin** [comment]
@amaseda Can you look at https://github.com/ga-dc/garnet/pull/482? I'd really, really like to get that taken care of before moving forward.

**Comment by andrewsunglaekim** [comment]
I like this, should this broken down into more component parts? ie more issues that way we can tag'em and bag'em?

**Comment by RobertAKARobin** [comment]
Go for it! I was just sorta word vomiting

**Comment by RobertAKARobin** [comment]
I'll close this
