### ISSUE TITLE
sensitive student data is visible in API endpoint

### ISSUE THREAD

**Issue by jshawl** [ga-dc/garnet#528]
![](https://dl.dropbox.com/s/ie0nc835n8g83uy/Screenshot%202016-03-08%2011.20.45.png?dl=0)

**Comment by jshawl** [comment]
can hide it here https://github.com/ga-dc/garnet/blob/04390e702a14ddfde701f3e25547b2eda8228a4e/app/models/user.rb#L124-L127 but how did it get there?

**Comment by adambray** [comment]
I think this is a result of Robin's PR that caches values on memberships? not sure.

**Comment by RobertAKARobin** [comment]
Yep, it is.

**Comment by jshawl** [comment]
how is it getting there? https://github.com/ga-dc/garnet/blob/79063b010f702dbaedf3fc6c044cd631dc57d53b/db/schema.rb#L134

**Comment by RobertAKARobin** [comment]
It must be these on memberships: https://github.com/ga-dc/garnet/blob/79063b010f702dbaedf3fc6c044cd631dc57d53b/db/schema.rb#L95

**Comment by adambray** [comment]
https://github.com/ga-dc/garnet/pull/537
