### ISSUE TITLE
Why is hw_complete all 0?

### ISSUE THREAD

**Issue by RobertAKARobin** [ga-dc/garnet#543]
Maybe solution is a "refresh all averages" button.

**Comment by jshawl** [comment]
@RobertAKARobin this is returning zero for submissions when at least one submission is "unmarked"

https://github.com/ga-dc/garnet/blame/6d958e08628e98ccbd6fede3fd3da733db8306d2/app/models/membership.rb#L55-L75

**Comment by jshawl** [comment]
<img width="736" alt="screen shot 2016-04-05 at 9 39 21 am" src="https://cloud.githubusercontent.com/assets/3824954/14316938/c9128f88-fbd3-11e5-99b0-d482b766a341.png">

**Comment by jshawl** [comment]
<img width="1449" alt="screen shot 2016-04-06 at 8 44 05 am" src="https://cloud.githubusercontent.com/assets/3824954/14316943/d01067c4-fbd3-11e5-8562-95ea79caa8bf.png">
