### ISSUE TITLE
Overriding GitHub Profile Info

### ISSUE THREAD

**Issue by timfoley** [ga-dc/garnet#554]
I'd like to be able to edit student names and override what is auto-populated by GitHub. Some of my students haven't put their full names into their profiles so they just show up as `clewinth` or `ragarza`. I've had students concerned about privacy and reluctant to put their names onto online profiles in the past, and in general, it'd just be easy for me to update their names myself.

**Comment by jshawl** [comment]
pseudocode:

```
current_user.cohorts.each do c
  c.memberships.each do m
    if current_user admins m
      current_user can edit user profile
    end
  end
end
```
