### ISSUE TITLE
Deleting student doesn't remove them from roster

### ISSUE THREAD

**Issue by thaddak0** [ga-dc/garnet#598]
deleting a student from a cohort doesn't remove them from the cohort's roster

**Comment by jshawl** [comment]
Can you please provide steps to reproduce this issue?

Currently, I can Manage cohort > Remove Member > see that they are gone on cohort show page

**Comment by thaddak0** [comment]
those were the steps I took, and the student I removed was still on the roster for a while but is not there anymore. sorry, thanks!
