### ISSUE TITLE
attendance is very strictly calculated 

### ISSUE THREAD

**Issue by thaddak0** [ga-dc/garnet#599]
in file `attendance.rb` the `calculate_status` method currently marks students as tardy if they don't sign in before the time of the event

suggest allowing students to consider being present if they sign in at the event_time or even giving a grace period

 ``` 
def calculate_status
    now = Time.now
    event_time = self.event.occurs_at
    if now < event_time
      Attendance.statuses[:present]
    elsif (now - event_time) < 4.hours
      Attendance.statuses[:tardy]
    else
      Attendance.statuses[:absent]
    end
  end
```

**Comment by jshawl** [comment]
@thaddak0 this calculation is intentional. If you want to give a grace period, you can "start" the event 15 minutes after you expect students to be there
